### PR TITLE
Allow to target the user configuration file

### PR DESCRIPTION
**Pull request by aruhier**
Add the boolean variable ssh_configuration_system_wide to target
/etc/ssh/ssh_config if true, ~/.ssh/config otherwise.

### CODE REVIEW

**Comment by evnm** [comment]
Thanks for the contribution! Exciting to see.

What if we instead added an `ssh_config_path` variable which defaults to `/etc/ssh/ssh_config`? It's mildly more annoying to override with a user's config file, but is more extensible and I think a bit more in line with Ansible's built-in modules (e.g. [`authorized_key`](http://docs.ansible.com/ansible/authorized_key_module.html)'s `path` parameter)

**Comment by aruhier** [comment]
I thought about that, but I didn't find many cases where it can be useful, that's why I used a boolean instead.

But you're right, it's more extensible to add a variable which contains the path, so yeah, it's probably a better choice !

**Comment by aruhier** [comment]
Do you want me to modify my PR or you prefer doing it ?

**Comment by evnm** [comment]
I think it would be useful in cases where you want to edit other (or multiple) user's ssh configs. Please update the PR and I'll merge it in.

**Comment by aruhier** [comment]
Hum, I didn't think about the multi-user thing… No problem, I update my PR ;)

**Comment by evnm** [comment]
Looks good. I squashed the two commits into a single one and merged the change. Thanks again!

**Comment by aruhier** [comment]
Cool, thanks

**Pull request closed without merging**
